In [1]:
import numpy as np
import pandas as pd

In [2]:
# Question 1: What is the version of numpy installed?
np.__version__
# Version is 1.20.1

'1.20.1'

In [3]:
# I had to click on the csv link and save as csv.
df = pd.read_csv(r'C:\Users\l676907\OneDrive - Cargill Inc\Desktop\ML_Zoomcamp\week-1-test/data.csv')

In [4]:
# Question 2: How many rows are in this dataset?
len(df)
# 11,914

11914

In [5]:
# Question 3: Who are the most frequent car manufacturers (top-3) according to the dataset?
df.Make.value_counts().head(3)
# Top 3 most frequent car manufacturers are Chevrolet, Ford, and Volkswagen.

Chevrolet     1123
Ford           881
Volkswagen     809
Name: Make, dtype: int64

In [6]:
# Question 4: What's the number of unique Audi car models in the dataset?
df[df['Make'] == 'Audi']['Model'].nunique()
# 34 unique Audi car models

34

In [7]:
# Question 5: How many columns in the dataset have missing values?
# df.isnull().sum()
(df.isnull().sum() != 0).sum()
# There are 5 columns with missing values

5

In [8]:
# Question 6:

# Part 1: Find the median value of "Engine Cylinders" column in the dataset.
df['Engine Cylinders'].median()
# The median value of "Engine Cylinders" is 6

6.0

In [10]:
# Part 2: Calculate the most frequent value of "Engine Cylinders"
mode_engine_cyl = df['Engine Cylinders'].mode()
mode_engine_cyl
# The mode value is 4

0    4.0
dtype: float64

In [11]:
# Part 3: Use the 'fillna' method to fill the missing values in "Engine Cylinders" 
# with the most frequent value from the previous step.
df['Engine Cylinders'] = df['Engine Cylinders'].fillna(mode_engine_cyl)
df['Engine Cylinders']

0        6.0
1        6.0
2        6.0
3        6.0
4        6.0
        ... 
11909    6.0
11910    6.0
11911    6.0
11912    6.0
11913    6.0
Name: Engine Cylinders, Length: 11914, dtype: float64

In [12]:
# part 4: Calculate the median value of "Engine Cylinders" again. Has it changed?
df['Engine Cylinders'].median()
# No, the median has not changed

6.0

In [13]:
# Question 7:
# Part 1: Select all the "Lotus" cars from the dataset.
lotus_df = df[df['Make'] == 'Lotus']
lotus_df.head()

Make  Model  Year             Engine Fuel Type  Engine HP  \
3912  Lotus  Elise  2009  premium unleaded (required)      189.0   
3913  Lotus  Elise  2009  premium unleaded (required)      218.0   
3914  Lotus  Elise  2009  premium unleaded (required)      189.0   
3915  Lotus  Elise  2010  premium unleaded (required)      189.0   
3916  Lotus  Elise  2010  premium unleaded (required)      218.0   

      Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
3912               4.0            MANUAL  rear wheel drive              2.0   
3913               4.0            MANUAL  rear wheel drive              2.0   
3914               4.0            MANUAL  rear wheel drive              2.0   
3915               4.0            MANUAL  rear wheel drive              2.0   
3916               4.0            MANUAL  rear wheel drive              2.0   

              Market Category Vehicle Size Vehicle Style  highway MPG  \
3912  Exotic,High-Performance      Compact   Convertible           27   
3913  Exotic,High-Performance      Compact   Convertible           26   
3914  Exotic,High-Performance      Compact   Convertible           27   
3915  Exotic,High-Performance      Compact   Convertible           27   
3916  Exotic,High-Performance      Compact   Convertible           26   

      city mpg  Popularity   MSRP  
3912        21         613  43995  
3913        20         613  54990  
3914        21         613  47250  
3915        21         613  47250  
3916        20         613  54990

In [14]:
# Part 2: Select only columns "Engine HP" and "Engine Cylinders"
lotus_df = lotus_df[['Engine HP', 'Engine Cylinders']]
lotus_df.head()

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3914      189.0               4.0
3915      189.0               4.0
3916      218.0               4.0

In [15]:
# Part 3: Now drop all duplicated rows using 'drop_duplicates' method (you should get a df with 9 rows).
lotus_df = lotus_df.drop_duplicates()

In [16]:
# Part 4: Get the underlying NumPy array. Let's call it "X"
X = lotus_df.to_numpy()
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [17]:
#Question 5: Compute matrix-matrix multiplication between the transpose of X and X. 
# To get the transpose, use X.T. Let's call the result XTX.
XTX = X.T @ X
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [18]:
# Question 6: Compute the inverse of XTX
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [19]:
# Question 7: Create an array y with values [1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800].
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

In [20]:
# Question 8: Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
w = (XTX_inv @ X.T) @ y
w[0]

4.594944810094576